In [13]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC, SVR
import seaborn as sns
import os
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, roc_curve, \
RocCurveDisplay, roc_auc_score, r2_score, mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss
from sklearn.naive_bayes import BernoulliNB, GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import VotingClassifier, VotingRegressor, BaggingClassifier,RandomForestClassifier,RandomForestRegressor, GradientBoostingClassifier, AdaBoostClassifier

In [14]:
glass = pd.read_csv('C:/Users/dbda.STUDENTSDC/Desktop/M.L/Cases/Glass_Identification/Glass.csv')
glass

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.00,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.00,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.00,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.00,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.00,0.0,building_windows_float_processed
...,...,...,...,...,...,...,...,...,...,...
209,1.51623,14.14,0.00,2.88,72.61,0.08,9.18,1.06,0.0,headlamps
210,1.51685,14.92,0.00,1.99,73.06,0.00,8.40,1.59,0.0,headlamps
211,1.52065,14.36,0.00,2.02,73.42,0.00,8.44,1.64,0.0,headlamps
212,1.51651,14.38,0.00,1.94,73.61,0.00,8.48,1.57,0.0,headlamps
213,1.51711,14.23,0.00,2.08,73.36,0.00,8.62,1.67,0.0,headlamps

In [20]:
x,y = glass.drop('Type',axis=1),glass['Type']

le = LabelEncoder()
y = le.fit_transform(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=25, stratify=y)

In [16]:
from sklearn.metrics import f1_score


gbm = GradientBoostingClassifier(random_state=25)
gbm.fit(x_train,y_train)
y_pred = gbm.predict(x_test)
f1_score(y_test,y_pred, average='macro')

0.7363826232247285

In [17]:
trees = [50, 100, 150, 200]
rates = [0.01, 0.1, 0.2, 0.5, 0.8]
depths = [None, 2, 3, 4, 5]
scores = []
for t in tqdm(trees):
    for r in rates:
        for d in depths:
            gbm = GradientBoostingClassifier(random_state=25, learning_rate=r, max_depth=d, n_estimators=t)
            gbm.fit(x_train,y_train)
            y_pred = gbm.predict(x_test)
            scores.append([t,d, r,f1_score(y_test,y_pred, average='macro')])

df_score = pd.DataFrame(scores,columns=['trees', 'depth','learning rate','score'])
df_score.sort_values('score',ascending=False)

  0%|          | 0/4 [00:09<?, ?it/s]

KeyboardInterrupt:

In [ ]:
adb = AdaBoostClassifier(random_state=25)
adb.fit(x_train, y_train)
y_pred = adb.predict(x_test)
print(accuracy_score(y_test, y_pred))

0.4461538461538462

XGBoost

In [18]:
from xgboost import XGBClassifier

In [21]:
trees = [50, 100, 150, 200]
rates = [0.01, 0.1, 0.2, 0.5, 0.8]
depths = [None, 2, 3, 4, 5]
scores = []
for t in tqdm(trees):
    for r in rates:
        for d in depths:
            xgb = XGBClassifier(random_state=25, learning_rate=r, max_depth=d, n_estimators=t)
            xgb.fit(x_train,y_train)
            y_pred = xgb.predict(x_test)
            scores.append([t,d, r,f1_score(y_test,y_pred, average='macro')])

df_score = pd.DataFrame(scores,columns=['trees', 'depth','learning rate','score'])
df_score.sort_values('score',ascending=False)

100%|██████████| 4/4 [00:16<00:00,  4.16s/it]

    trees  depth  learning rate     score
85    200    NaN           0.20  0.832031
35    100    NaN           0.20  0.824693
60    150    NaN           0.20  0.824693
84    200    5.0           0.10  0.824693
49    100    5.0           0.80  0.817927
..    ...    ...            ...       ...
1      50    2.0           0.01  0.580505
28    100    4.0           0.01  0.573782
26    100    2.0           0.01  0.573671
3      50    4.0           0.01  0.565793
2      50    3.0           0.01  0.559242

[100 rows x 4 columns]

LightGBM

In [22]:
! pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (2.3.3)
Requirement already satisfied: scipy in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from lightgbm) (1.16.3)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------------------------------------ --- 1.3/1.5 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 7.0 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [24]:
from lightgbm import LGBMClassifier

trees = [50, 100, 150, 200]
rates = [0.01, 0.1, 0.2, 0.5, 0.8]
depths = [None, 2, 3, 4, 5]
scores = []
for t in tqdm(trees):
    for r in rates:
        for d in depths:
            lgb = LGBMClassifier(random_state=25, verbose = -1, learning_rate=r, max_depth=d, n_estimators=t)
            lgb.fit(x_train,y_train)
            y_pred = lgb.predict(x_test)
            scores.append([t,d, r,f1_score(y_test,y_pred, average='macro')])

df_score = pd.DataFrame(scores,columns=['trees', 'depth','learning rate','score'])
df_score.sort_values('score',ascending=False)

100%|██████████| 4/4 [00:06<00:00,  1.66s/it]

    trees  depth  learning rate     score
40    100    NaN           0.50  0.854124
65    150    NaN           0.50  0.846927
90    200    NaN           0.50  0.846927
66    150    2.0           0.50  0.839529
87    200    3.0           0.20  0.831932
..    ...    ...            ...       ...
0      50    NaN           0.01  0.378053
4      50    5.0           0.01  0.378053
3      50    4.0           0.01  0.378053
2      50    3.0           0.01  0.364575
1      50    2.0           0.01  0.327790

[100 rows x 4 columns]

In [25]:
! pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: pandas>=0.24 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (6.3.1)
Requirement already satisfied: six in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\dbda.studentsdc\appdata\local\programs\python\python313\lib\site-packages (from plotly->catboost) (2.7.0)
Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl (102.4 MB)
   ---------------------------------------- 0.0/102.4 MB ? eta -:--:--
    --------------------------------------- 1.3/102.4 MB 10.7 MB/s eta 0:00:10
   -- ------------------------------------- 6.6/102.4 MB 19.1 MB/s eta 0:00:06
   ------- -------------------------------- 18.1/102.4 MB 33.5 MB/s eta 0:00:03
   ------------ --------------------------- 32.8/102.4 MB 44.2 MB/s eta 0:00:02
   ------------------ --------------------- 48.5/102.4 MB 51.3 MB/s eta 0:00:02
   ------------------------ --------------- 63.4/102.4 MB 56.3 MB/s eta 0:00:01
   ----------------------------- ---------- 76.3/102.4 MB 56.6 MB/s eta 0:00:01
   -------------------------------- ------- 83.6/102.4 MB 53.9 MB/s eta 0:00:01
   ------------------------------------ --- 92.3/102.4 MB 52.6 MB/s eta 0:00:01
   --------------------------------------  100.7/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 51.5 MB/s eta 0:00:01
   ---------------------------------------- 102.4/102.4 MB 30.2 MB/s  0:00:03
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   ---------------------------------------- 0/2 [graphviz]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.8 graphviz-0.21

CatBoost

In [26]:
from catboost import CatBoostClassifier

In [27]:
x,y = glass.drop('Type',axis=1),glass['Type']

# le = LabelEncoder()
# y = le.fit_transform(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=25, stratify=y)

In [28]:
trees = [50, 100, 150, 200]
rates = [0.01, 0.1, 0.2, 0.5, 0.8]
depths = [None, 2, 3, 4, 5]
scores = []
for t in tqdm(trees):
    for r in rates:
        for d in depths:
            ctb = CatBoostClassifier(random_state=25, verbose = False, learning_rate=r, max_depth=d, n_estimators=t)
            ctb.fit(x_train,y_train)
            y_pred = ctb.predict(x_test)
            scores.append([t,d, r,f1_score(y_test,y_pred, average='macro')])

df_score = pd.DataFrame(scores,columns=['trees', 'depth','learning rate','score'])
df_score.sort_values('score',ascending=False)

100%|██████████| 4/4 [00:35<00:00,  8.97s/it]

    trees  depth  learning rate     score
20     50    NaN           0.80  0.853940
95    200    NaN           0.80  0.853940
70    150    NaN           0.80  0.853940
45    100    NaN           0.80  0.853940
99    200    5.0           0.80  0.845659
..    ...    ...            ...       ...
28    100    4.0           0.01  0.365543
77    200    3.0           0.01  0.365543
2      50    3.0           0.01  0.364659
27    100    3.0           0.01  0.363680
3      50    4.0           0.01  0.351629

[100 rows x 4 columns]