In [22]:
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC, SVR
import seaborn as sns
import os
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, roc_curve, \
RocCurveDisplay, roc_auc_score, r2_score, mean_absolute_error, f1_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.naive_bayes import BernoulliNB, GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import VotingRegressor, BaggingClassifier, BaggingRegressor, RandomForestClassifier, RandomForestRegressor
from sklearn.linear_model import ridge_regression, ElasticNet
from sklearn.linear_model import Ridge

In [23]:
import warnings
warnings.filterwarnings('ignore')

importing df directly from uci website into pandas df

In [24]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
taiwanese_bankruptcy_prediction = fetch_ucirepo(id=572) 
  
# data (as pandas dataframes) 
X = taiwanese_bankruptcy_prediction.data.features 
y = taiwanese_bankruptcy_prediction.data.targets 
  
# metadata 
print(taiwanese_bankruptcy_prediction.metadata) 
  
# variable information 
print(taiwanese_bankruptcy_prediction.variables)

{'uci_id': 572, 'name': 'Taiwanese Bankruptcy Prediction', 'repository_url': 'https://archive.ics.uci.edu/dataset/572/taiwanese+bankruptcy+prediction', 'data_url': 'https://archive.ics.uci.edu/static/public/572/data.csv', 'abstract': 'The data were collected from the Taiwan Economic Journal  for the years 1999 to 2009. Company bankruptcy was defined based on the business regulations of the Taiwan Stock Exchange.', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 6819, 'num_features': 95, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['Bankrupt?'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2020, 'last_updated': 'Fri Mar 15 2024', 'dataset_doi': '10.24432/C5004D', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': None, 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': "The first attribute is the class lable.\r\nX1\tCost of Interest-bearing Debt\r\nX2\tCash Reinvestment Ratio\r\nX3\tCurrent Ratio\r\nX4\tAcid Test  \r\nX5\tInterest Expenses/Total Revenue\r\nX6\tTotal Liability/Equity Ratio\r\nX7\tLiability/Total Assets\r\nX8\tInterest-bearing Debt/Equity\r\nX9\tContingent Liability/Equity\r\nX10\tOperating Income/Capital\r\nX11\tPretax Income/Capital\r\nX12\tWorking Capital to Total Assets\r\nX13\tQuick Assets/Total assets\r\nX14\tCurrent Assets/Total Assets\r\nX15\tCash/Total Assets\r\nX16\tQuick Assets/Current Liability\r\nX17\tCash/Current Liability\r\nX18\tCurrent Liability to Assets\r\nX19\tOperating Funds to Liability \r\nX20\tInventory/Working Capital\r\nX21\tInventory/Current Liability\r\nX22\tCurrent Liabilities/Liability\r\nX23\tWorking Capital/Equity\r\nX24\tCurrent Liabilities/Equity\r\nX25\tLong-term Liability to Current Assets\r\nX26\tCurrent Liability to Current Assets\r\nX27\tOne if Total Liability exceeds Total Assets;\r\nX28\tEquity to Liability\r\nX29\tEquity/Total Assets\r\nX30\t(Long-term Liability+Equity)/Fixed Assets\r\nX31\tFixed Assets to Assets\r\nX32\tCurrent Liability to Liability \r\nX33\tCurrent Liability to Equity\r\nX34\tEquity to Long-term Liability\r\nX35\tLiability to Equity \r\nX36\tDegree of Financial Leverage\r\nX37\tInterest Coverage Ratio\r\nX38\tOperating Expenses/Net Sales\r\nX39\t(Research and Development Expenses)/Net Sales\r\nX40\tEffective Tax Rate\r\nX41\tBook Value Per Share(B)\r\nX42\tBook Value Per Share(A)\r\nX43\tBook Value Per Share(C)\r\nX44\tCash Flow Per Share\r\nX45\tSales Per Share\r\nX46\tOperating Income Per Share\r\nX47\tSales Per Employee\r\nX48\tOperation Income Per Employee\r\nX49\tFixed Assets Per Employee\r\nX50\ttotal assets to GNP price\r\nX51\tReturn On Total Assets(C)\r\nX52\tReturn On Total Assets(A)\r\nX53\tReturn On Total Assets(B)\r\nX54\tGross Profit /Net Sales\r\nX55\tRealized Gross Profit/Net Sales\r\nX56\tOperating Income /Net Sales\r\nX57\tPre-Tax Income/Net Sales\r\nX58\tNet Income/Net Sales\r\nX59\tNet Non-operating Income Ratio\r\nX60\tNet Income-Exclude Disposal Gain or Loss/Net Sales\r\nX61\tEPS-Net Income\r\nX62\tPretax Income Per Share\r\nX63\tRetained Earnings to Total Assets\r\nX64\tTotal Income to Total Expenses\r\nX65\tTotal Expenses to Assets\r\nX66\tNet Income to Total Assets\r\nX67\tGross Profit to Sales\r\nX68\tNet Income to Stockholder's Equity\r\nX69\tOne if Net Income is Negative for the Last Two Years; Zero Otherwise\r\nX70\t(Inventory +Accounts Receivables) /Equity\r\nX71\tTotal Asset Turnover\r\nX72\tAccounts Receivable Turnover\r\nX73\tDays Receivable Outstanding\r\nX74\tInventory Turnover\r\nX75\tFixed Asset Turnover\r\nX76\tEquity Turnover\r\nX77\tCurrent Assets to Sales\r\nX78\tQuick Assets to Sales\r\nX79\tWorking Capital to Sales\r\nX80\tCash to Sales\r\nX81\tCash Flow to Sales\r\nX82\tNo-credit Interval\r\nX83\tCash Flow from Operating/Current Liabilities\r\nX84\tCash Flow to Total Assets\r\nX85\tCash Flow to Liability\r\nX86\tCFO to Assets\r\nX87\tCash Flow to Equity\r\nX88\tRealized Gross Profit Growth Rate\r\nX89\tOperating Income Growth\r\nX90\tNet Income Growth\r\nX91\tContinuing Operating Income after Tax Growth\r\nX92\tNet Income-Excluding Disposal Gain or Loss Growth\r\nX93\tTotal Asset Growth\r\nX94\tTotal Equity Growth\r\nX95\tReturn on Total Asset Growth\r\n", 'citation': None}}
                                                 name     role        type  \
0                                           Bankrupt?   Target     Integer
1    ROA(C) before interest and depreciation befor...  Feature  Continuous
2              ROA(A) before interest and % after tax  Feature  Continuous
3    ROA(B) before interest and depreciation after...  Feature  Continuous
4                              Operating Gross Margin  Feature  Continuous
..                                                ...      ...         ...
91                                Liability to Equity  Feature  Continuous
92                 Degree of Financial Leverage (DFL)  Feature  Continuous
93   Interest Coverage Ratio (Interest expense to ...  Feature  Continuous
94                                    Net Income Flag  Feature     Integer
95                                Equity to Liability  Feature  Continuous

   demographic description units missing_values
0         None        None  None             no
1         None        None  None             no
2         None        None  None             no
3         None        None  None             no
4         None        None  None             no
..         ...         ...   ...            ...
91        None        None  None             no
92        None        None  None             no
93        None        None  None             no
94        None        None  None             no
95        None        None  None             no

[96 rows x 7 columns]

In [25]:
y.value_counts()

Bankrupt?
0            6599
1             220
Name: count, dtype: int64

In [26]:
y.value_counts(normalize=True)*100

Bankrupt?
0            96.77372
1             3.22628
Name: proportion, dtype: float64

In [27]:
X

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,0.780985,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,0.781506,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,0.780284,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,0.781241,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,0.781550,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,0.781588,...,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,1,0.029890
6815,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,0.781586,...,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,1,0.038284
6816,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,0.781546,...,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,1,0.097649
6817,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,0.781663,...,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,1,0.044009
6818,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,0.786079,...,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,1,0.233902

In [28]:
y

      Bankrupt?
0             1
1             1
2             1
3             1
4             1
...         ...
6814          0
6815          0
6816          0
6817          0
6818          0

[6819 rows x 1 columns]

In [29]:
x_train, x_test, y_train, y_test = train_test_split(X,y, random_state=25, test_size=0.3)

In [30]:
features = [2,3,4,5]
n_est = [25, 50, 100, 150, 200]
scores = []
for f in tqdm(features):
    for n in n_est:
        rf = RandomForestRegressor(random_state = 25, max_features=f, n_estimators=n)
        rf.fit(x_train, y_train)
        y_pred = rf.predict(x_test)
        scores.append([f,n,mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(data = scores, columns = ['No. of Features', 'No of Estimators', 'score'])
df_scores.sort_values('score', ascending=True)

100%|██████████| 4/4 [00:24<00:00,  6.17s/it]

    No. of Features  No of Estimators     score
6                 3                50  0.049638
8                 3               150  0.049925
7                 3               100  0.050098
9                 3               200  0.050142
11                4                50  0.050156
5                 3                25  0.050166
10                4                25  0.050420
18                5               150  0.050538
13                4               150  0.050557
12                4               100  0.050577
14                4               200  0.050687
3                 2               150  0.050749
4                 2               200  0.050760
17                5               100  0.050831
2                 2               100  0.050846
19                5               200  0.050872
16                5                50  0.051056
1                 2                50  0.051193
15                5                25  0.051222
0                 2                25  0.051652

In [31]:
features = [2,3,4,5]
n_est = [25, 50, 100, 150, 200]
scores = []
for f in tqdm(features):
    for n in n_est:
        rf = RandomForestClassifier(random_state = 25, max_features=f, n_estimators=n)
        rf.fit(x_train, y_train)
        y_pred = rf.predict(x_test)
        scores.append([f,n,f1_score(y_test, y_pred, pos_label=1)])

df_scores = pd.DataFrame(data = scores, columns = ['No. of Features', 'No of Estimators', 'score'])
df_scores.sort_values('score', ascending=False)

100%|██████████| 4/4 [00:27<00:00,  6.98s/it]

    No. of Features  No of Estimators     score
10                4                25  0.340909
11                4                50  0.285714
2                 2               100  0.282051
6                 3                50  0.275000
17                5               100  0.265060
19                5               200  0.258824
15                5                25  0.258065
18                5               150  0.255814
3                 2               150  0.253165
0                 2                25  0.250000
12                4               100  0.250000
5                 3                25  0.250000
7                 3               100  0.243902
1                 2                50  0.240964
8                 3               150  0.240964
4                 2               200  0.233766
9                 3               200  0.219512
16                5                50  0.211765
13                4               150  0.210526
14                4               200  0.207792

In [32]:
df_scores.sort_values('score', ascending=False)

    No. of Features  No of Estimators     score
10                4                25  0.340909
11                4                50  0.285714
2                 2               100  0.282051
6                 3                50  0.275000
17                5               100  0.265060
19                5               200  0.258824
15                5                25  0.258065
18                5               150  0.255814
3                 2               150  0.253165
0                 2                25  0.250000
12                4               100  0.250000
5                 3                25  0.250000
7                 3               100  0.243902
1                 2                50  0.240964
8                 3               150  0.240964
4                 2               200  0.233766
9                 3               200  0.219512
16                5                50  0.211765
13                4               150  0.210526
14                4               200  0.207792

Classification Report

In [34]:
best_model = RandomForestClassifier(random_state = 25, max_features=4, n_estimators=25)
best_model.fit(x_train, y_train)
y_pred = best_model.predict(x_test)
# scores.append([f,n,f1_score(y_test, y_pred, pos_label=1)])
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1983
           1       0.60      0.24      0.34        63

    accuracy                           0.97      2046
   macro avg       0.79      0.62      0.66      2046
weighted avg       0.96      0.97      0.97      2046

using wine dataset

In [35]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
wine = fetch_ucirepo(id=109) 
  
# data (as pandas dataframes) 
X = wine.data.features 
y = wine.data.targets 
  
# metadata 
print(wine.metadata) 
  
# variable information 
print(wine.variables)

{'uci_id': 109, 'name': 'Wine', 'repository_url': 'https://archive.ics.uci.edu/dataset/109/wine', 'data_url': 'https://archive.ics.uci.edu/static/public/109/data.csv', 'abstract': 'Using chemical analysis to determine the origin of wines', 'area': 'Physics and Chemistry', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 178, 'num_features': 13, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1992, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C5PC7J', 'creators': ['Stefan Aeberhard', 'M. Forina'], 'intro_paper': {'ID': 246, 'type': 'NATIVE', 'title': 'Comparative analysis of statistical pattern recognition methods in high dimensional settings', 'authors': 'S. Aeberhard, D. Coomans, O. Vel', 'venue': 'Pattern Recognition', 'year': 1994, 'journal': None, 'DOI': '10.1016/0031-3203(94)90145-7', 'URL': 'https://www.semanticscholar.org/paper/83dc3e4030d7b9fbdbb4bde03ce12ab70ca10528', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'These data are the results of a chemical analysis of wines grown in the same region in Italy but derived from three different cultivars. The analysis determined the quantities of 13 constituents found in each of the three types of wines. \r\n\r\nI think that the initial data set had around 30 variables, but for some reason I only have the 13 dimensional version. I had a list of what the 30 or so variables were, but a.)  I lost it, and b.), I would not know which 13 variables are included in the set.\r\n\r\nThe attributes are (dontated by Riccardo Leardi, riclea@anchem.unige.it )\r\n1) Alcohol\r\n2) Malic acid\r\n3) Ash\r\n4) Alcalinity of ash  \r\n5) Magnesium\r\n6) Total phenols\r\n7) Flavanoids\r\n8) Nonflavanoid phenols\r\n9) Proanthocyanins\r\n10)Color intensity\r\n11)Hue\r\n12)OD280/OD315 of diluted wines\r\n13)Proline \r\n\r\nIn a classification context, this is a well posed problem with "well behaved" class structures. A good data set for first testing of a new classifier, but not very challenging.           ', 'purpose': 'test', 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'All attributes are continuous\r\n\t\r\nNo statistics available, but suggest to standardise variables for certain uses (e.g. for us with classifiers which are NOT scale invariant)\r\n\r\nNOTE: 1st attribute is class identifier (1-3)', 'citation': None}}
                            name     role         type demographic  \
0                          class   Target  Categorical        None
1                        Alcohol  Feature   Continuous        None
2                      Malicacid  Feature   Continuous        None
3                            Ash  Feature   Continuous        None
4              Alcalinity_of_ash  Feature   Continuous        None
5                      Magnesium  Feature      Integer        None
6                  Total_phenols  Feature   Continuous        None
7                     Flavanoids  Feature   Continuous        None
8           Nonflavanoid_phenols  Feature   Continuous        None
9                Proanthocyanins  Feature   Continuous        None
10               Color_intensity  Feature   Continuous        None
11                           Hue  Feature   Continuous        None
12  0D280_0D315_of_diluted_wines  Feature   Continuous        None
13                       Proline  Feature      Integer        None

   description units missing_values
0         None  None             no
1         None  None             no
2         None  None             no
3         None  None             no
4         None  None             no
5         None  None             no
6         None  None             no
7         None  None             no
8         None  None             no
9         None  None             no
10        None  None             no
11        None  None             no
12        None  None             no
13        None  None             no

In [36]:
y.value_counts()

class
2        71
1        59
3        48
Name: count, dtype: int64