In [43]:
import pandas as pd
import numpy as np

Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks
Display column names of the DF
Show min/max and average marks
Get unique values and student count for each Department

In [44]:
data=[{'name':"Max", "Age":22, "dept":"DBDA","Marks":93},
    {'name':"Sam", "Age":19, "dept":"DAC","Marks":63},
      {'name':"Bob", "Age":24, "dept":"DITIS","Marks":73},
      {'name':"NOVA", "Age":26, "dept":"VLSI","Marks":82},
     ]

df = pd.DataFrame(data)
df

   name  Age   dept  Marks
0   Max   22   DBDA     93
1   Sam   19    DAC     63
2   Bob   24  DITIS     73
3  NOVA   26   VLSI     82

In [45]:
df.columns

Index(['name', 'Age', 'dept', 'Marks'], dtype='object')

In [46]:
min_marks = df["Marks"].min()
print("max marks: ",min_marks)

max_marks = df["Marks"].max()
print("max marks: ",max_marks)

avg_marks = df["Marks"].mean() #mean is use for find avarage value
print("avg marks: ",avg_marks)

max marks:  63
max marks:  93
avg marks:  77.75

Q2. Read csv file solar.csv
Display all the plants with capacity > 500 MW
Display plant details for New York plant
For all the plants display Average MW Per Plant and Generation (GWh)
Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
List top 5 plants for their Generation
Display all plant details for states – California, Nevada, Arizona and Texas
Group the plants by region, find – min/max capacity plant for each group
Add following information to the existing details for the plants

In [47]:
df=pd.read_csv('solar.csv')
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [48]:
#Display all the plants with capacity > 500 MW
data=df[df['Installed Capacity (MW)']>500]
data

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
7,Florida,15,535,12.3,453,South

In [49]:
#Display plant details for New York plant
newyork_plant=df[df['State']=='New York']
newyork_plant

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [63]:
#For all the plants display Average MW Per Plant and Generation (GWh)
data1=df[['State','Average MW Per Plant','Generation (GWh)'], set_index='State']
data1

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2658702170.py, line 2)

In [51]:
#Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
sorted=df.sort_values(by=['Generation (GWh)','Installed Capacity (MW)'], ascending=[True,False])
sorted

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

In [52]:
#List top 5 plants for their Generation
top5=df.sort_values(by='Generation (GWh)', ascending=False).head(5)
top5

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

In [53]:
#Display all plant details for states – California, Nevada, Arizona and Texas
data2=df[df['State'].isin( ['California','Nevada','Arizona','Texas'])]
data2

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

In [56]:
#Group the plants by region, find – min/max capacity plant for each group
data3 = df.groupby('Region')['Installed Capacity (MW)'].min()
print(data3)

data3 = df.groupby('Region')['Installed Capacity (MW)'].max()
print(data3)

Region
East      53
North    261
South    187
West     238
Name: Installed Capacity (MW), dtype: int64
Region
East      118
North     261
South     535
West     4395
Name: Installed Capacity (MW), dtype: int64

In [60]:
new_row = ['North Carolina', 148, 669, 4.5, 1162, 'North']

# Add row correctly
df = pd.concat([df, pd.DataFrame([new_row], columns=df.columns)], ignore_index=True)

print(df)

ValueError: 12 columns passed, passed data had 6 columns