In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [9]:
a = np.array([[10, 200, 0.3],
              [9, 230, 0.1],
              [8, 240, 0.24],
              [9.5, 225, 0.45]])
pa = pd.DataFrame(a, columns=['X1', 'X2', 'X3'])
print("Means: \n", pa.mean())
print("Std Deviations: \n", pa.std(ddof=0))

Means:
 X1      9.1250
X2    223.7500
X3      0.2725
dtype: float64
Std Deviations:
 X1     0.739510
X2    14.737283
X3     0.125574
dtype: float64

In [7]:
scaler = StandardScaler().set_output(transform='pandas')
scaler.fit(pa)
print(scaler.mean_)
print(scaler.scale_)

[  9.125  223.75     0.2725]
[ 0.73950997 14.73728265  0.12557368]

In [13]:
scaler.transform(pa)

     X1     X2        X3
0  1.00  0.000  0.571429
1  0.50  0.750  0.000000
2  0.00  1.000  0.400000
3  0.75  0.625  1.000000

In [11]:
scaler = MinMaxScaler().set_output(transform='pandas')
scaler.fit(pa)
print(scaler.data_min_)
print(scaler.data_max_)

[8.e+00 2.e+02 1.e-01]
[ 10.   240.     0.45]

In [12]:
scaler.transform(pa)

     X1     X2        X3
0  1.00  0.000  0.571429
1  0.50  0.750  0.000000
2  0.00  1.000  0.400000
3  0.75  0.625  1.000000