In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, roc_curve, RocCurveDisplay, roc_auc_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss

import os

In [3]:
boston = pd.read_csv("Datasets/Boston.csv")
X = boston.drop('medv', axis=1)
y = boston['medv']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.neighbors import KNeighborsRegressor


Ks = np.arange(1,16)
scores = []
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.head()

   k    scores
0  1  4.300000
1  2  4.500000
2  3  4.563158
3  4  4.384868
4  5  4.276316

In [33]:
from sklearn.discriminant_analysis import StandardScaler

knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
mean_absolute_error(y_test, y_pred)

16956.60569105691

In [34]:

scaler = StandardScaler().set_output(transform='pandas')

X_trn_scl = scaler.fit_transform(X_train)
knn = KNeighborsRegressor(n_neighbors=3)
knn.fit(X_trn_scl, y_train)

X_tst_scl = scaler.transform(X_test)
y_pred = knn.predict(X_tst_scl)
mean_absolute_error(y_test, y_pred)

13699.07520325203

In [35]:
#Running same loop as above for scaled data
Ks = np.arange(1,16)
scores = []
for k in Ks:
    scaler = StandardScaler().set_output(transform='pandas')

    X_trn_scl = scaler.fit_transform(X_train)
    knn = KNeighborsRegressor(n_neighbors=3)
    knn.fit(X_trn_scl, y_train)

    X_tst_scl = scaler.transform(X_test)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.head()

   k        scores
0  1  13699.075203
1  2  13699.075203
2  3  13699.075203
3  4  13699.075203
4  5  13699.075203

#### Housing

In [36]:
from sklearn.compose import ColumnTransformer, make_column_selector


housing = pd.read_csv('Datasets/Housing.csv')
X, y = housing.drop('price', axis=1), housing['price']
ohe = OneHotEncoder(drop='first', sparse_output=False).set_output(transform='pandas')
col_trnf = ColumnTransformer([('OHE', ohe, make_column_selector(dtype_include=object) )],
                             remainder='passthrough',
                             verbose_feature_names_out=False)
col_trnf = col_trnf.set_output(transform='pandas')
X = col_trnf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [37]:
Ks = np.arange(1,16)
scores = []
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.sort_values('scores', ascending=True)

     k        scores
2    3  16956.605691
4    5  16974.496341
5    6  17033.884146
13  14  17095.358014
3    4  17185.521341
14  15  17270.135772
11  12  17344.276931
10  11  17398.662417
12  13  17427.580675
6    7  17518.982578
9   10  17540.569512
8    9  17575.090786
7    8  17592.823171
1    2  18987.347561
0    1  22645.731707

In [38]:
Ks = np.arange(1,16)
scores = []

scaler = StandardScaler().set_output(transform='pandas')
X_trn_scl = scaler.fit_transform(X_train)
X_tst_scl = scaler.transform(X_test)

for k in Ks:
    
    knn = KNeighborsRegressor(n_neighbors=3)
    knn.fit(X_trn_scl, y_train)

    
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.sort_values('scores', ascending=True)

     k        scores
0    1  13699.075203
1    2  13699.075203
2    3  13699.075203
3    4  13699.075203
4    5  13699.075203
5    6  13699.075203
6    7  13699.075203
7    8  13699.075203
8    9  13699.075203
9   10  13699.075203
10  11  13699.075203
11  12  13699.075203
12  13  13699.075203
13  14  13699.075203
14  15  13699.075203

#### Concrete Strength

In [40]:
conc = pd.read_csv("Cases/Concrete_Strength/Concrete_Data.csv")
X, y = conc.drop('Strength', axis=1), conc['Strength']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [41]:
Ks = np.arange(1,16)
scores = []

scaler = StandardScaler().set_output(transform='pandas')
X_trn_scl = scaler.fit_transform(X_train)
X_tst_scl = scaler.transform(X_test)

for k in Ks:
    
    knn = KNeighborsRegressor(n_neighbors=3)
    knn.fit(X_trn_scl, y_train)

    
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.sort_values('scores', ascending=True)

     k    scores
0    1  6.559687
1    2  6.559687
2    3  6.559687
3    4  6.559687
4    5  6.559687
5    6  6.559687
6    7  6.559687
7    8  6.559687
8    9  6.559687
9   10  6.559687
10  11  6.559687
11  12  6.559687
12  13  6.559687
13  14  6.559687
14  15  6.559687

#### Chemical Data

In [43]:
chem = pd.read_csv('Cases/Chemical Process Data/ChemicalProcess.csv')
X, y = chem.drop('Yield', axis=1), chem['Yield']

##### Mean Strategy

In [64]:
from sklearn.impute import SimpleImputer

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

imputer = SimpleImputer(strategy='mean')
scaler = StandardScaler()
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)

##### without scaling

In [67]:
Ks = np.arange(1,16)
scores = []
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_imp, y_train)
    y_pred = knn.predict(X_tst_imp)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.sort_values('scores', ascending=True)

     k    scores
4    5  1.258113
2    3  1.324088
3    4  1.331651
1    2  1.335566
11  12  1.343035
10  11  1.347684
12  13  1.348273
14  15  1.356642
5    6  1.361195
13  14  1.361671
9   10  1.376623
6    7  1.385553
8    9  1.390671
7    8  1.404127
0    1  1.666981

##### Median Stratigy

In [66]:
imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()
X_trn_imp = imputer.fit_transform(X_train)
X_tst_imp = imputer.transform(X_test)
X_trn_scl = scaler.fit_transform(X_trn_imp)
X_tst_scl = scaler.transform(X_tst_imp)

In [68]:
Ks = np.arange(1,16)
scores = []
for k in Ks:
    knn = KNeighborsRegressor(n_neighbors=k)
    knn.fit(X_trn_scl, y_train)
    y_pred = knn.predict(X_tst_scl)
    scores.append([k, mean_absolute_error(y_test, y_pred)])

df_scores = pd.DataFrame(scores, columns=['k', 'scores'])
df_scores.sort_values('scores', ascending=True)

     k    scores
2    3  1.040063
1    2  1.043396
3    4  1.057830
6    7  1.094879
5    6  1.095566
4    5  1.101849
7    8  1.108656
8    9  1.138616
9   10  1.144849
10  11  1.147530
11  12  1.154025
12  13  1.165631
14  15  1.180440
13  14  1.184811
0    1  1.323019

### Pipe-line